import Mathlib
import Mathlib.Tactic

theorem theorem_684564_problem
  (theta : ℝ)
  (f : ℕ → ℕ → ℝ)
  (P_H : ℕ → ℝ)
  (P_L_cond_H : ℕ → ℕ → ℝ)
  (P_L : ℕ → ℝ)
  (k : ℕ)
  (h_theta_pos : 0 < theta)
  (h_poisson : ∀ h, P_H h = Real.exp (-theta) * theta ^ h / h.factorial)
  (h_approx : ∀ h k, P_L_cond_H k h = f h k)
  (h_total_prob : ∀ k, P_L k = ∑' h, P_L_cond_H k h * P_H h) :
  P_L k = ∑' h, (Real.exp (-theta) * theta ^ h / h.factorial) * f h k := by
  sorry













theorem theorem_685674_problem 
  (τ : TopologicalSpace ℝ)
  (hτ : ∀ s : Set ℝ, @IsClosed ℝ τ s ↔ s.Countable ∨ s = Set.univ) :
  ¬ @Continuous (ℝ × ℝ) ℝ (@instTopologicalSpaceProd ℝ ℝ τ τ) τ (fun p => p.1 + p.2) := by
  sorry

theorem theorem_685664_problem 
  (X1 X2 : ℝ → ℝ) 
  (c : ℝ) 
  (hc : c ≠ 0)
  (Y : ℝ → ℝ)
  (t0 : ℝ)
  (hY_def : ∀ t, Y t = (1 / c * (X2 t)^2)^2 - (X1 t)^2)
  (h_preserve : ∀ t, Y t = Y t0)
  (h_init : Y t0 = 0) :
  ∀ t, t ≥ t0 → Y t = 0 := by
  sorry

theorem theorem_685842_problem
  (Mg Mw T alpha V V0 t : ℝ)
  (hMg : Mg > 0)
  (hMw : Mw > 0)
  (hT : T > 0)
  (ht : 0 ≤ t ∧ t ≤ T)
  (h_eq : (1 / (2 * Mw)) * Real.log (abs ((Mg * T^2 + Mw * T^2) / (Mg * T^2 + Mw * T^2 - Mw * t^2))) =
          (1 / (2 * Mw)) * Real.log ((T * alpha + 2 * Mw * V) / (T * alpha + 2 * Mw * V0))) :
  (Mg * T^2 + Mw * T^2) / (Mg * T^2 + Mw * T^2 - Mw * t^2) =
  (T * alpha + 2 * Mw * V) / (T * alpha + 2 * Mw * V0) := by
  sorry

theorem theorem_686037_problem (r : Setoid ℝ) :
  (Countable (Quotient r) ∧ Infinite (Quotient r)) ↔ Cardinal.mk (Quotient r) = Cardinal.mk ℕ := by
  sorry

theorem theorem_686190_problem :
  ∃ f : ℝ → ℝ, (∀ x : ℕ → ℝ, CauchySeq x → CauchySeq (f ∘ x)) ∧ ¬ UniformContinuous f := by
  sorry



theorem theorem_686214_problem (n : ℕ) (a c : ℕ → ℕ → ℝ) (b : ℕ → ℝ) :
  ∑ k in Finset.range (n + 1), ∑ i in Finset.range (k + 1), a k i * b i * c k i =
  ∑ i in Finset.range (n + 1), b i * ∑ k in Finset.Ico i (n + 1), a k i * c k i := by
  sorry

theorem theorem_685882_problem
  {M : Type*}
  -- ψ and φ are time-dependent symplectomorphisms, modeled as time-dependent invertible maps.
  (ψ φ : ℝ → M ≃ M)
  -- H and G are the corresponding Hamiltonians.
  (H G : ℝ → M → ℝ)
  -- A predicate abstracting the relation "flow is generated by Hamiltonian" on the symplectic manifold.
  (is_generated_by : (ℝ → M ≃ M) → (ℝ → M → ℝ) → Prop)
  -- Condition: ψ is generated by H
  (h1 : is_generated_by ψ H)
  -- Condition: φ is generated by G
  (h2 : is_generated_by φ G) :
  -- Conclusion: The composition ψ ∘ φ is generated by H + G ∘ ψ⁻¹
  is_generated_by (fun t => (φ t).trans (ψ t)) (fun t x => H t x + G t ((ψ t).symm x)) := by
  sorry









theorem theorem_686390_problem (h R : ℝ) (h_pos : 0 < h) (R_pos : 0 < R)
  (z : ℝ → ℝ) (hz : ∀ r, z r = h - (h / R) * r) :
  2 * Real.pi * ∫ r in (0)..R, r * z r = (Real.pi * h * R ^ 2) / 3 := by
  sorry







theorem theorem_686732_problem (a K x : ℝ)
  (ha : a ≠ 0)
  (hx : x + a ≠ 0)
  (hK : K + a * (x + a) ≠ 0) :
  let y := fun t ↦ (t + a) / (K + a * (t + a))
  deriv y x = (y x - a * (y x)^2) / (x + a) := by
  sorry

theorem theorem_686127_problem
  {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]
  (f : E →L[ℂ] ℂ) :
  ‖f‖ = ‖Complex.reCLM.comp (f.restrictScalars ℝ)‖ := by
  sorry

theorem theorem_686595_problem (f : ℝ → ℝ) (c : ℝ)
  (h_diff : DifferentiableAt ℝ (deriv f) c)
  (h1 : deriv f c = 0)
  (h2 : deriv (deriv f) c > 0) :
  IsLocalMin f c := by
  sorry



theorem theorem_686753_problem 
  (n m : ℕ) 
  (K₀ : Set (Matrix (Fin n) (Fin m) ℂ))
  (h : ∀ (i : Fin n) (j : Fin m), IsCompact ((fun A => A i j) '' K₀)) :
  IsCompact (⋃ (i : Fin n) (j : Fin m), (fun A => A i j) '' K₀) := by
  sorry

theorem theorem_686708_problem
  {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (x₀ : E) (r₀ : ℝ) (x : E)
  (h_r0 : r₀ > 0)
  (h_x : ‖x‖ ≤ 1) :
  x₀ + (r₀ / 2) • x ∈ Metric.ball x₀ r₀ := by
  sorry





theorem theorem_686738_problem :
  ∃ (X : Type) (S : Set (Set X)),
    (∀ A ∈ S, ∀ B ∈ S, A ∪ B ∈ S) ∧
    (∃ (A : ℕ → Set X), (∀ i, A i ∈ S) ∧ (⋃ i, A i) ∉ S) := by
  sorry

theorem theorem_687026_problem (R M n : ℕ) (h : n ≤ R + M) :
  ∑ k in Finset.range (n + 1), Nat.choose R k * Nat.choose M (n - k) = Nat.choose (R + M) n := by
  sorry

theorem theorem_686547_problem
  (n : ℕ) (hn : n ≥ 2)
  (X : Type)
  (P₀ P₁ P₂ : X → X → Prop)
  (σ : (i : Fin n) → (j : Fin n) → i ≠ j → Fin 3) :
  ∃! χ : (Fin n → X) → Prop, ∀ x : Fin n → X,
    χ x ↔ ∀ (i j : Fin n) (h : i ≠ j),
      (σ i j h = 0 → P₀ (x i) (x j)) ∧
      (σ i j h = 1 → P₁ (x i) (x j)) ∧
      (σ i j h = 2 → P₂ (x i) (x j)) := by
  sorry

theorem theorem_687092_problem
  (φ : ℝ × ℝ → ℝ) (hφ : φ = Prod.fst)
  (f : ℝ → ℝ) (hf : ContDiff ℝ 1 f)
  (p : ℝ × ℝ) (v : ℝ × ℝ) :
  let φ_star_f := f ∘ φ
  let φ_push_v := fderiv ℝ φ p v
  fderiv ℝ f (φ p) φ_push_v = fderiv ℝ φ_star_f p v := by
  sorry



theorem theorem_686977_problem
  (A : Type*) [Ring A]
  (B : Subring A)
  (M : Type*) [AddCommGroup M] [Module A M] :
  ∃ (h : Module B M), ∀ (b : B) (m : M), h.smul b m = (b : A) • m := by
  sorry

theorem theorem_686750_problem (g : ℝ → ℝ) (hg : ContDiff ℝ ⊤ g)
  (f : ℝ → ℝ) (hf : f = λ x ↦ Real.exp (g x))
  (phi : ℝ → ℝ)
  (hphi : ∀ x, phi x = (iteratedDeriv 4 g x) + 3 * (iteratedDeriv 2 g x)^2 + 
                       (iteratedDeriv 1 g x)^4 + 4 * (iteratedDeriv 3 g x) * (iteratedDeriv 1 g x) + 
                       6 * (iteratedDeriv 1 g x)^2 * (iteratedDeriv 2 g x))
  (h_deriv_formula : ∀ x, iteratedDeriv 4 f x = Real.exp (g x) * phi x)
  (h_g4_neg : ∀ x, iteratedDeriv 4 g x < 0)
  (h_g3_nonneg : ∀ x, iteratedDeriv 3 g x ≥ 0)
  (h_g4_mono : MonotoneOn (iteratedDeriv 4 g) (Set.Ici 0))
  (h_g3_mono : AntitoneOn (iteratedDeriv 3 g) (Set.Ici 0))
  (h_g4_lim : Filter.Tendsto (iteratedDeriv 4 g) Filter.atTop (nhds 0))
  (h_g3_lim : Filter.Tendsto (iteratedDeriv 3 g) Filter.atTop (nhds 0))
  (h_phi_neg_zero : phi 0 < 0)
  (h_phi_pos_inf : ∃ L, ∀ x > L, phi x > 0) :
  ∃ x₁ > 0, (∀ x ∈ Set.Ico 0 x₁, iteratedDeriv 4 f x < 0) ∧ 
            (∀ x ∈ Set.Ioi x₁, iteratedDeriv 4 f x > 0) := by
  sorry





theorem theorem_687005_problem (n : ℕ) (θ : ℝ) :
  ∫ y in θ..(θ + 1), (n : ℝ) * y * (y - θ) ^ (n - 1) =
  (∫ u in (0 : ℝ)..1, (n : ℝ) * u ^ n) +
  ∫ y in θ..(θ + 1), (n : ℝ) * θ * (y - θ) ^ (n - 1) := by
  sorry



theorem theorem_687504_problem
  (x : ℕ → ℕ → ℕ)
  (hx : ∀ i j, x i j = 0 ∨ x i j = 1)
  (y : ℕ → ℕ)
  (hy : ∀ j, y j = 1 - x j j) :
  ∀ i, x i ≠ y := by
  sorry



theorem theorem_688042_problem
  {G H : Type*}
  [Group G] [TopologicalSpace G] [TopologicalGroup G]
  [Group H] [TopologicalSpace H]
  (ψ : G →* H)
  (h_cont : Continuous ψ)
  (K : Subgroup G)
  (hK_ker : K ≤ ψ.ker)
  (hK_compact : IsCompact (K : Set G))
  (hK_open : IsOpen (K : Set G)) :
  IsOpen (ψ.ker : Set G) := by
  sorry

theorem theorem_687866_problem (S : AddSubgroup ℚ) :
  Nonempty (S ≃+ ℤ) ↔ ∃ q : ℚ, q ≠ 0 ∧ (S : Set ℚ) = {x | ∃ n : ℤ, x = q * (n : ℚ)} := by
  sorry

theorem theorem_686925_problem (n : ℕ) (hn : n ≥ 4) :
  let G : SimpleGraph (Fin n) := ⊤
  let S := Finset.Icc 1 (n.choose 2)
  ¬ ∃ f : Sym2 (Fin n) → ℕ,
    (∀ e ∈ G.edgeFinset, f e ∈ S) ∧
    (Set.InjOn f G.edgeSet) ∧
    (∀ v₁ v₂ v₃ v₄ : Fin n,
      v₁ ≠ v₂ → v₂ ≠ v₃ → v₃ ≠ v₄ →
      v₁ ≠ v₃ → v₂ ≠ v₄ →
      Nat.gcd (f (Sym2.mk (v₁, v₂))) (f (Sym2.mk (v₃, v₄))) ∣ f (Sym2.mk (v₂, v₃))) := by
  sorry

theorem theorem_687403_problem (a b : ℝ)
  (f : ℝ → ℝ) (u : ℝ → ℝ)
  (hf : ∀ x, f x = 1 / Real.sqrt (1 + Real.exp (2 * x)))
  (hu : ∀ x, u x = 1 + Real.exp (2 * x))
  (h : u a = u b) :
  ∫ x in a..b, f x = 0 := by
  sorry

theorem theorem_687508_problem
  (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] [FiniteDimensional ℝ H]
  (V : Submodule ℝ H)
  (P : H →L[ℝ] H)
  (hP : ∀ x, P x = (orthogonalProjection V x : H))
  (u v : H) :
  ‖P u - P v‖^2 ≤ inner (v - u) (P v - P u) := by
  sorry







theorem theorem_687831_problem
  (a ε : ℝ) (hε : 1 < ε) (ha : 0 < a)
  (Λ : ℝ) (hΛ : Λ = (1 - ε^2) * a)
  (r1 θ1 : ℝ)
  (h_branch : r1 - Real.sqrt ((r1 * Real.cos θ1 + 2 * a * ε)^2 + (r1 * Real.sin θ1)^2) = 2 * a) :
  r1 = Λ / (1 + ε * Real.cos θ1) := by
  sorry





theorem theorem_688185_problem (α K t_n : ℝ) (hα : 0 < α) (hK : 0 < K) :
  HasDerivAt (fun t => α^2 * (Real.exp (K * (t - t_n)) - 1)) (α^2 * K) t_n := by
  sorry



theorem theorem_687800_problem (D : Set ℝ) (hD : ¬ IsPreconnected D) :
  ∃ f : D → ℝ, ∃ a b : D, ∃ c : ℝ, f a < c ∧ c < f b ∧ ∀ x : D, f x ≠ c := by
  sorry





theorem theorem_688197_problem
  (n m : ℕ)
  (f : (Fin n → ℝ) → (Fin m → ℝ))
  (γ : ℝ → (Fin n → ℝ))
  (h : ℝ → (Fin m → ℝ))
  (t : ℝ)
  (hf : Differentiable ℝ f)
  (hg : Differentiable ℝ γ)
  (hh : h = f ∘ γ) :
  deriv h t = (fderiv ℝ f (γ t)) (deriv γ t) := by
  sorry

theorem theorem_688490_problem (F₁ F₂ : Matrix (Fin 3) (Fin 3) ℝ) :
  ∃ P : Polynomial ℝ, P.degree ≤ 3 ∧ ∀ α : ℝ, P.eval α = Matrix.det (α • F₁ + (1 - α) • F₂) := by
  sorry

theorem theorem_687889_problem
  (f g : ℝ × ℝ → ℝ)
  (u : ℕ → ℝ × ℝ)
  (m b : ℝ)
  (α β : ℝ)
  (hf : Continuous f)
  (hg : Continuous g)
  (h_conv : Filter.Tendsto u Filter.atTop (nhds (m, b)))
  (h_g_seq : ∀ n, g (u n) > β)
  (h_g_lim : g (m, b) > β)
  (h_f_lim : f (m, b) > α) :
  ∃ N, ∀ n ≥ N, f (u n) > α := by
  sorry



theorem theorem_688483_problem :
  ∃ (A B C : Type) (g : A → B) (h : A → C),
  Function.Injective (fun x ↦ (g x, h x)) ∧
  ¬ (Function.Injective g ∧ Function.Injective h) := by
  sorry

theorem theorem_687730_problem
  (k : ℕ)
  (D : Set ℝ)
  (f : ℝ → ℝ)
  (F : ℝ → ℝ → (Fin k → ℝ) → ℝ)
  (hf : ContDiffOn ℝ k f D)
  (hF_sol : ∀ x ∈ D, F x (f x) (fun i => iteratedDeriv (i + 1) f x) = 0) :
  ∀ x ∈ D, ∀ y : ℝ, F x y (fun i => iteratedDeriv (i + 1) f x) = 0 ↔ y = f x := by
  sorry

theorem theorem_688417_problem (a : ℕ → ℝ)
  (h1 : a 1 = Real.pi / 4)
  (h2 : ∀ n, 1 ≤ n → a (n + 1) = Real.cos (a n)) :
  ∀ n, 1 ≤ n → a n ∈ Set.Icc (1 / Real.sqrt 2) (Real.pi / 4) := by
  sorry

theorem theorem_688621_problem
  (K L : Type*) [Field K] [Field L] [Algebra K L]
  (η η' : L)
  (h_alg_η : IsAlgebraic K η)
  (h_alg_η' : IsAlgebraic K η')
  (h_notin_K : η ∉ (⊥ : IntermediateField K L))
  (h_notin_K' : η' ∉ (⊥ : IntermediateField K L))
  (h_eq : IntermediateField.adjoin K {η} = IntermediateField.adjoin K {η'}) :
  let f := minpoly K η
  let g := minpoly K η'
  Nonempty (f.SplittingField ≃ₐ[K] g.SplittingField) := by
  sorry

theorem theorem_688651_problem
  (N : ℕ)
  (specs : List (ℕ × ℕ))
  (h_distinct : specs.Pairwise (fun a b => a.1 ≠ b.1))
  (h_pos : ∀ p ∈ specs, p.1 > 0)
  (h_total : (specs.map (fun p => p.1 * p.2)).sum = N)
  (α : Type*) [Fintype α] [DecidableEq α] (h_card : Fintype.card α = N) :
  (Finset.filter (fun P : Finset (Finset α) =>
    P.biUnion id = Finset.univ ∧
    (∀ A ∈ P, ∀ B ∈ P, A ≠ B → Disjoint A B) ∧
    (∀ A ∈ P, A ≠ ∅) ∧
    ∀ p ∈ specs, (P.filter (fun A => A.card = p.1)).card = p.2
  ) ((Finset.univ : Finset α).powerset.powerset)).card =
  N.factorial / (specs.map (fun p => (p.1.factorial ^ p.2) * p.2.factorial)).prod := by
  sorry

theorem theorem_688485_problem
  (n : ℕ)
  {V : Type*}
  [NormedAddCommGroup V]
  [InnerProductSpace ℝ V]
  (e : Basis (Fin n) ℝ V)
  (G : Matrix (Fin n) (Fin n) ℝ)
  (hG : G = Matrix.of (fun i j => inner (e i) (e j)))
  (hG_inv : IsUnit G.det)
  (f : Fin n → V)
  (hf : ∀ i, f i = ∑ j, (G⁻¹ i j) • e j) :
  ∀ i k, inner (f i) (f k) = G⁻¹ i k := by
  sorry







theorem theorem_688142_problem (a : ℕ → ℕ → ℂ) (x t : ℂ)
  (h_bound : ∃ C : ℝ, ∀ m n : ℕ, ‖a m n‖ ≤ C)
  (hx : ‖x‖ < 1) (ht : ‖t‖ < 1) :
  Summable (fun p : ℕ × ℕ => ‖a p.1 p.2 * x ^ p.1 * t ^ p.2‖) := by
  sorry



theorem theorem_688916_problem :
  ∑' n : ℕ, (n : ℝ)^3 / (Nat.factorial n : ℝ) = 5 * Real.exp 1 := by
  sorry



theorem theorem_689106_problem (m1 m2 k c1 c2 : ℕ)
  (h1 : c1 = m1 ^^^ k)
  (h2 : c2 = m2 ^^^ k) :
  c1 ^^^ c2 = m1 ^^^ m2 := by
  sorry

theorem theorem_688881_problem 
  (X : Type*) 
  (f : X → ℝ) 
  (y : ℝ) 
  (h : ℕ → ℝ) 
  (A : ℕ → Set X)
  (h_pos : ∀ n, 0 < h n)
  (h_lim : Filter.Tendsto h Filter.atTop (nhds 0))
  (h_def : ∀ n, A n = f ⁻¹' (Set.Icc y (y + h n)))
  (h_mono : ∀ n, ∃ m ≥ n, ∀ k, m < k → A k ⊆ A n) :
  Filter.Tendsto A Filter.atTop (nhds (f ⁻¹' {y})) := by
  sorry

theorem theorem_689070_problem
  (F : Type*) [Field F]
  (V : Type*) [AddCommGroup V] [Module F V]
  (E : Subfield F) :
  ∃ (m : Module E V), ∀ (a : E) (v : V), m.smul a v = (a : F) • v := by
  sorry



theorem theorem_688617_problem (n m : ℕ) (M : Fin n → Option (Fin m)) :
  let E : ℤ := Finset.sum Finset.univ (fun i => 
    match M i with
    | some j => abs ((i : ℤ) - (j : ℤ))
    | none => (max n m : ℤ))
  E ≥ 0 := by
  sorry

theorem theorem_689231_problem (S : Set ℝ) (hS : MeasurableSet S) :
  Measurable (Set.indicator S (fun _ ↦ (1 : ℝ))) := by
  sorry



theorem theorem_688940_problem
  (f : Polynomial ℤ)
  (p₁ p₂ : ℕ)
  (hp₁ : Nat.Prime p₁)
  (hp₂ : Nat.Prime p₂)
  (h_distinct : p₁ ≠ p₂)
  (h_irred₁ : Irreducible (Polynomial.map (Int.castRingHom (ZMod p₁)) f))
  (h_irred₂ : Irreducible (Polynomial.map (Int.castRingHom (ZMod p₂)) f)) :
  Irreducible f := by
  sorry



theorem theorem_689435_problem
  (a b : ℕ → ℝ)
  (h_abs_a : Summable (fun n ↦ |a n|))
  (h_conv_b : Summable b)
  (c : ℕ → ℝ)
  (h_c : ∀ n, c n = ∑ k in Finset.range (n + 1), a k * b (n - k)) :
  Summable c ∧ (∑' n, c n) = (∑' n, a n) * (∑' n, b n) := by
  sorry

theorem theorem_689709_problem {α : Type*} (E : ℕ → Set α)
  (h : ∀ n, (E n).Countable) :
  (⋃ n, E n).Countable := by
  sorry



theorem theorem_689347_problem
  {U V W : Type*}
  [NormedAddCommGroup U] [NormedSpace ℝ U]
  [NormedAddCommGroup V] [NormedSpace ℝ V]
  [NormedAddCommGroup W] [NormedSpace ℝ W]
  (B : U → V) (A : V → W) (c : U)
  (hB : DifferentiableAt ℝ B c)
  (hB2 : DifferentiableAt ℝ (fderiv ℝ B) c)
  (hA : DifferentiableAt ℝ A (B c))
  (hA2 : DifferentiableAt ℝ (fderiv ℝ A) (B c)) :
  ∀ (u v : U),
    fderiv ℝ (fderiv ℝ (A ∘ B)) c u v =
    fderiv ℝ (fderiv ℝ A) (B c) (fderiv ℝ B c u) (fderiv ℝ B c v) +
    fderiv ℝ A (B c) (fderiv ℝ (fderiv ℝ B) c u v) := by
  sorry







theorem theorem_689617_problem (f : ℝ → ℝ → ℝ → ℝ) (a c d x : ℝ)
  (h_cont : Continuous (fun (p : ℝ × ℝ × ℝ) ↦ f p.1 p.2.1 p.2.2))
  (h_cont_partial : Continuous (fun (p : ℝ × ℝ × ℝ) ↦ deriv (fun u ↦ f u p.2.1 p.2.2) p.1)) :
  let g := fun (u v : ℝ) ↦ ∫ z in c..d, f u v z
  deriv (fun u ↦ ∫ y in a..u, g u y) x =
  g x x + ∫ y in a..x, ∫ z in c..d, deriv (fun u ↦ f u y z) x := by
  sorry











theorem theorem_689836_problem
  (n : ℕ) (f g : ℝ → ℝ) (x₀ : ℝ)
  (hf : ContDiff ℝ ⊤ f) (hg : ContDiff ℝ ⊤ g)
  (h_eq : ∀ k ≤ n, iteratedDeriv k f x₀ = iteratedDeriv k g x₀)
  (h_neq : iteratedDeriv (n + 1) f x₀ ≠ iteratedDeriv (n + 1) g x₀) :
  IsGreatest { m : ℕ | ∀ k ≤ m, iteratedDeriv k f x₀ = iteratedDeriv k g x₀ } n := by
  sorry

